### ISSUE TITLE
Library is not running in xcode 7.3.

### ISSUE THREAD

**Issue by EMakadiya** [tnadus/iOS-VideoKit-TRIAL#1]
Hi,

When I build in xcode 7.3 it gives me below error.

```
Undefined symbols for architecture x86_64:
  "_clock_gettime", referenced from:
      _av_gettime_relative in libavutil.a(time.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see `invocation)
```
Its running in xcode 8.1.

Please help me to run this in xcode 7.3.

Thanks,
Ekta

**Comment by tnadus** [comment]
Hi, 2.6 version supports only xcode 8.1 but how about trying the 2.5 version ?
